### ISSUE TITLE
worldmap

### ISSUE THREAD

**Issue by berak** [StevenPuttemans/own_website_hugo_code#1]
hey ;)

just got curious about the *infamous* worldmap.

quick look at the src revealed this:

https://github.com/StevenPuttemans/own_website_hugo_code/blob/e18e65d425ee8d6ab5ed0d3d20d6a61a0ae49289/static/tmap.html#L4-L7

*my* localhost does not serve anything here: http://localhost:1313

just remove the `http://localhost:1313/` part from those urls, and it *should* find the missing files [here](https://github.com/StevenPuttemans/own_website_hugo_code/tree/master/static/jvmap)

nice evening ;)

**Comment by StevenPuttemans** [comment]
Hi @berak and thanks for having a look at this!

This is the exact reason why it did not work on my cellphone and did on the net :+1: , because it was still cached there ... will fix this at once!
